### ISSUE TITLE
LazyMobXTable resets filtering when selecting a checkbox 

### ISSUE THREAD

**Issue by oplantalech** [cBioPortal/cbioportal-frontend#1071]
![2018-04-06 11 30 09](https://user-images.githubusercontent.com/20278013/38414193-0edf1802-398e-11e8-8d0f-3792aca9efbe.gif)

When filtering the table using the search box, and then clicking one of the checkboxes, the table re-renders, thus the filtering is lost. Is it possible to avoid these resetting of the filtering when clicking one of the checkboxes?

You can find the code for the "Volcano Plot Popup" in the rc branch, which was implemented here: #830.

**Comment by alisman** [comment]
@oplantalech, I've asked @onursumer to help you figure this out out.  I'm pretty sure we've seen this before.   It must have to do with where the state for the filter is being kept.

**Comment by alisman** [comment]
@oplantalech when you get the instance up (for debugging volcano plot issue) let @onursumer know so we can look at this one too.

**Comment by oplantalech** [comment]
@alisman @onursumer Here you can see the problem: https://cbioportal-test.thehyve.net:8081/cbioportal/

**Comment by onursumer** [comment]
@oplantalech currently, I am getting a `Service Unavailable` error. Is the server down?
