### ISSUE TITLE
Modify React Mutation Table to support multiple samples [Adam]

### ISSUE THREAD

**Issue by adamabeshouse** [cBioPortal/cbioportal-frontend#116]
Shows which samples have the mutation in each row

**Comment by ecerami** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Testing](https://trello.com/c/V7smbW6r/1-testing)

**Comment by onursumer** [comment]
A high level generic specification of this issue should be something like this: Allow a single row in the mutation table to represent multiple mutations.

Basically, we are merging multiple mutations into one row.

And for this specific case, for a single row we should group mutations by mutation events. And we should be able to render multiple values for sample specific columns (values that differ in each separate sample) such as allele frequency values, and tumors (sample ids).

@adamabeshouse @jjgao @ecerami: Correct me if I miss something.

**Comment by ecerami** [comment]
Yes, that's it.  As an example, see:  http://www.cbioportal.org/case.do?cancer_study_id=prad_fhcrc&case_id=00-010

![screenshot_1436](https://cloud.githubusercontent.com/assets/1009066/21436666/b2ab0332-c84d-11e6-8056-abce1b101b6f.png)

**Comment by onursumer** [comment]
In addition to `Tumors`, `Allel Freq`, and `Allel Freq (N)` columns, we also need to merge values for `Variant Reads`, `Variant Reads (N)`, `Ref Reads`, and `Ref Reads (N)` columns.

Here is a mapping showing the different names we use for these columns:

| Patient View (legacy)  | Results Page (legacy) | Mutation Table (current WIP)  | Mutation model (API) |
|-------------------------------|------------------------------|----------------------------|-------------------------------|
Ref Reads (N) | Norm Ref | Ref Count (N) | normalRefCount
Variant Reads (N) | Norm Alt | Alt Count (N) | normalAltCount
Ref Reads       | Var Ref | Ref Count (T) | tumorRefCount
Variant Reads | Var Alt | Alt Count (T) | tumorAltCount

@adamabeshouse @jjgao @ecerami Do you think, for consistency, we should use same column names for all mutation table instances we have in portal?

**Comment by adamabeshouse** [comment]
It's not clear to me how we would display an arbitrary number of these in a single Td. Bar chart?

**Comment by adamabeshouse** [comment]
Another question is what's the best way to get in the sample data necessary for the Tumors column tooltips: tumor type and cancer type.

**Comment by onursumer** [comment]
Legacy implementation simply shows those values together with sample ids:

![variant_reads](https://cloud.githubusercontent.com/assets/3604198/21461235/b8b0ac66-c91d-11e6-9731-bfab43b612a3.png)

We should probably improve that at some point, but for now I guess we can keep it like that.

**Comment by onursumer** [comment]
@adamabeshouse For tumor type and cancer type, we will need another API call. But for now we only use mock data. I think soon we need to discuss how/where to make the API calls for additional data.

**Comment by ecerami** [comment]
@onursumer @adamabeshouse:  can you clarify where you need the new API calls?  I don't see this in the URL above:  http://www.cbioportal.org/case.do?cancer_study_id=prad_fhcrc&case_id=00-010

**Comment by jjgao** [comment]
@adamabeshouse don't worry about tumor type and cancer type in the tooltip. The info in the top part of the page should be re-used so no API is needed specifically for the mutations table for that purpose. For the moment, if you cannnot get that information, please put the `sample id` only.
