### ISSUE TITLE
Volcano plot points are not colored in release versions

### ISSUE THREAD

**Issue by oplantalech** [cBioPortal/cbioportal-frontend#1208]
When using the release versions of cBioPortal, the volcano plot has its points displayed in grey, and they don't change their color once selected (although the functionality works). However, when I use the release branch in the frontend (with `localStorage.setItem("localdev",true)`), the points of the plot are colored, and they change their color once selected. How can this be fixed?

You can take a look at the screenshots for more clarity:
![volcano_plot_without_color](https://user-images.githubusercontent.com/20278013/40720973-8b40489e-6418-11e8-9c54-d2d9efa25f86.png)
![volcano_plot_with_color](https://user-images.githubusercontent.com/20278013/40720974-8b5b18c2-6418-11e8-873f-b99d45e47c6e.png)

**Comment by alisman** [comment]
@oplantalech which is the desired functionality?  I assume the one currently in production (grayscale)?

**Comment by inodb** [comment]
@oplantalech Have you tried setting the latest frontend commit in `portal/pom.xml`? Maybe it just needs an update to the frontend.

It could also be that the behavior is different with the same commit when using localdev=true vs the bundled artifacts. You could try running `npm run build`, install http-server and run `./node_modules/http-server/bin/http-server --cors dist/ -p 3000`. Then run with `localdist=true`.

**Comment by oplantalech** [comment]
@alisman No, the desired one is the NON-gray one

**Comment by oplantalech** [comment]
@inodb This also happens using the last commit of `release-1.14.0` in the `portal/pom.xml`.

**Comment by alisman** [comment]
Hey Oleg, yeah, we just need to see it browser and I'm sure it will be very apparent what's going on.

**Comment by oplantalech** [comment]
@alisman @inodb Here you have the link: https://cbioportal-test.thehyve.net:8081/cbioportal/

FYI: this was not happening in version 1.13.1.

**Comment by oplantalech** [comment]
Fixed here: https://github.com/cBioPortal/cbioportal-frontend/pull/1251
