### ISSUE TITLE
Methylation heatmap color scale

### ISSUE THREAD

**Issue by angelicaochoa** [cBioPortal/cbioportal-frontend#1229]
Methylation heatmap track color scale should have a midpoint of 0.35 (on a range from 0 to 1)

General methylation data interpretations:
-  < 0.2 = hypomethylated
- 0.2 - 0.49 = mid methylation range (ave = 0.35)
- \> 0.49 = hypermethylated

**Comment by adamabeshouse** [comment]
the way we can do it in the oncoprint is by specifying stop points, and colors for those stop points, then everything in between is linearly interpolated between the sandwiching stop points. so you're saying the stop points should be [0, 0.2, 0.35(?), 0.49, 1] ? and what colors?

**Comment by angelicaochoa** [comment]
@adamabeshouse I'm meeting with the investigator tomorrow - will follow up afterwards with colors/stop points. Thanks!

**Comment by angelicaochoa** [comment]
@adamabeshouse let's make 0.35 the midpoint, colors the same as they are now 

0 - black
0.35 - gray
1 - red

**Comment by adamabeshouse** [comment]
cool, what should the gray color be?

**Comment by angelicaochoa** [comment]
@adamabeshouse  Can you use the attached image as an example w/these ranges (mentioned above):

-  < 0.2 = hypomethylated 
- 0.2 - 0.49 = mid methylation range (ave = 0.35)
- \> 0.49 = hypermethylated

blue = hypomethylation
white = mid methylation
red = hypermethylation

![meth-heatmap-color-scale](https://user-images.githubusercontent.com/15623749/42051147-1b38e02e-7ad9-11e8-8058-4d94db8ccc56.png)

**Comment by adamabeshouse** [comment]
https://github.com/cBioPortal/cbioportal-frontend/pull/1269
