### ISSUE TITLE
use icons in toolbar (and add tooltips)

### ISSUE THREAD

**Issue by alisman** [cBioPortal/cbioportal-frontend#134]
The icons i used are all font awesome, so you can just use
<i className="fa fa-eye" ></i>

fa-cloud-download
fa-clipboard
fa-arrow-left
fa-arrow-right

**Comment by onursumer** [comment]
@alisman I think what we need for arrows are:
`fa-angle-left`
`fa-angle-right`

**Comment by alisman** [comment]
ah yes.  sorry

**Comment by onursumer** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fix Mutation Table Header (Next/Previous Buttons)](https://trello.com/c/Yp2VjevE/68-fix-mutation-table-header-next-previous-buttons)

**Comment by onursumer** [comment]
fixed by https://github.com/cBioPortal/cbioportal-frontend/pull/131
