### ISSUE TITLE
Add "PRIORITY" support for clinical events

### ISSUE THREAD

**Issue by pieterlukasse** [cBioPortal/cbioportal-frontend#1460]
Idea: introduce "PRIORITY" support for clinical events. This could be similar to the [already existing concept of priority implemented for clinical attributes](https://github.com/cBioPortal/cbioportal/blob/master/docs/File-Formats.md#data-files) and [used in the study view](https://github.com/cBioPortal/cbioportal/blob/master/docs/Study-View.md), where priority is a numeric value to rank items, and rank 0 is used to hide items by default (items can still be added manually by users).

We could add `PRIORITY` to the list of fields [documented here](https://github.com/cBioPortal/cbioportal/blob/master/docs/File-Formats.md#data-file-9) as a special  generic field for all EVENT_TYPEs .

By using this `PRIORITY` field, one could have easy control over which event types appear and where they appear in the timeline. E.g. one could easily configure Lab tests to appear before (op top) Treatments.

Items configured to initially not appear (`PRIORITY=0`), could still be displayed after clicking on a "show all" button, like shown in the mockup below:

![image](https://user-images.githubusercontent.com/2900303/45686155-f6a8d080-bb4b-11e8-93e2-012eced8f465.png)

**Use case:** this feature will especially be useful for adding emphasis on events of some types, e.g. LAB_TESTS. In this way the most significant lab tests could be displayed by default, while other inconclusive tests could be hidden by default (and thus not taking up unnecessary space and not cluttering the patient view with less valuable information).

**Comment by pieterlukasse** [comment]
@schultzn @jjgao I am interested in getting your view on this one. Thanks!

**Comment by schultzn** [comment]
I like the idea. So we would need an additional meta file for the timeline data? Or do we already have that?

**Comment by pieterlukasse** [comment]
@schultzn no new meta file needed. Only change in data formats and validation/loading scripts is to make `PRIORITY` an officially supported "special effect" column, similar to the existing ones like `EVENT_TYPE` and `SPECIMEN_REFERENCE_NUMBER` here https://github.com/cBioPortal/cbioportal/blob/master/docs/File-Formats.md#data-file-9

**Comment by schultzn** [comment]
I see. Wouldn’t a global meta file be easier and more useful though? Or is it advantageous to be able to set the priority for each patient individually?

**Comment by pieterlukasse** [comment]
@schultzn yes, it will be advantageous to set it per patient. For example, in the use case I mentioned: a specific lab test result could be significant for one patient but inconclusive for another one.

**Comment by schultzn** [comment]
Yes, but who would have the bandwidth to adjust this setting at a patient level? There could be hundreds or thousands of patients in a cohort.

**Comment by pieterlukasse** [comment]
Good point. The way I see it now is: for larger cohorts, we are assuming the clinical data / event data is transformed and generated by scripts. The priority can be added automatically by these scripts based on specific configuration or other rules relevant for the study in question. For smaller cohorts, this can be added by hand if no transformation scripts are available. Regardless of the size of the cohort, manual adjustments are still easy if the goal is to reorder only based on event type: since each event type can have its own file, it is just a matter of populating the PRIORITY column with a static value for all rows in that file. 

Anyway, if the goal is to also reorder (or hide) individual events based on more complex rules, e.g. order or hide lab tests based on a certain score, then having the configuration only at a global level (i.e. per event type) does not suffice. 

For clarity, below is an example of the PRIORITY column added to a clinical event data file (:

**without PRIORITY column**
![image](https://user-images.githubusercontent.com/2900303/45700012-c709c080-bb6b-11e8-8a8c-1fcf023e8804.png)


**with new PRIORITY column**
![image](https://user-images.githubusercontent.com/2900303/45700087-f4ef0500-bb6b-11e8-90eb-a1b62920c1d2.png)

**Comment by jjgao** [comment]
Issue moved to [cBioPortal/cbioportal #5642](https://github.com/cBioPortal/cbioportal/issues/5642) via [**ZenHub**](https://www.zenhub.com/)
