### ISSUE TITLE
Show/hide options no longer work

### ISSUE THREAD

**Issue by ecerami** [cBioPortal/cbioportal-frontend#149]
On this page:  http://cbioportal-frontend-demo.herokuapp.com/?cancer_study_id=lgg_ucsf_2014&case_id=P04

when I click show/hide, I can't select any additional columns.

**Comment by onursumer** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [(3) fix show/hide](https://trello.com/c/6TQmq9rC/86-3-fix-show-hide)
