### ISSUE TITLE
cbioportal-frontend Error "TS2451: Cannot redeclare block-scoped variable 'name'."

### ISSUE THREAD

**Issue by naveen-mred** [cBioPortal/cbioportal-frontend#1534]
I am trying to install cbioportal-frontend-1.16.0 local installation with node version 8.11.4 and npm version 6.4.1.
while command "npm run start" is used 
ERROR in /home/trainee_biocos/RecatApp_Examples/cbioportalTestRun/cbioportal-frontend-1.16.0/node_modules/typescript/lib/lib.dom.d.ts(15165,15):
TS2451: Cannot redeclare block-scoped variable 'name'.
Version: typescript 2.7.2
Time: 37647ms

webpack: Compiled successfully.
This is output.
when browsed to "localhost:3000/" no content gets loaded except title.

**Comment by naveen-mred** [comment]
I was using master. Now i am using Custom where set to localhost:8080/cbioportal. default page when i type localhost:3000/ it gets redirected to localhost:3000/study. From localhost:8080/cbioportal it seems working after setting localStorage.setItem("localdev",true). "http://localhost:3000/mutation_mapper" this works. All the time I was thinking localhost:3000/ will load cbioportal frontend. I was looking to work on query part of website.

**Comment by inodb** [comment]
closing b/c original issue was solved - let us know if u run into any other issues
