### ISSUE TITLE
RC is broken

### ISSUE THREAD

**Issue by oplantalech** [cBioPortal/cbioportal-frontend#1902]
After selecting a study, the profile selection does not appear. I see a bunch of errors in the console, which are a repetition of these:
![captura de pantalla 2019-01-09 a les 15 58 31](https://user-images.githubusercontent.com/20278013/50907425-a4a3f780-1427-11e9-96e5-4db14d181a7e.png)

**Comment by zhx828** [comment]
@oplantalech we recently upgraded the react. Please do `npm install` and `npm run build`

**Comment by oplantalech** [comment]
@zhx828 thanks, problem solved1 😃
