### ISSUE TITLE
Show error when patient/sample does not exist

### ISSUE THREAD

**Issue by inodb** [cBioPortal/cbioportal-frontend#205]
In case of going to a URL where there's no patient/sample, show a message that no patient or sample with that id was found. Only in log is a good start.

**Comment by latifaabdullayeva** [comment]
Hi @inodb, 

After reading the source code, I came up with a few questions:
 - Do we need to show error message based on response from API or just local validation?
 - Are there any specific requirements to ids of patients / samples?

Thank you.
