### ISSUE TITLE
Genomic Overview - Make distinction between sequenced, but no mutations & not sequenced

### ISSUE THREAD

**Issue by inodb** [cBioPortal/cbioportal-frontend#215]
Currently it seems both cases are shown in the same way.

**Comment by adamabeshouse** [comment]
If that's true then it's a bug, not sequenced has a light gray, sequenced but no mutations is a darker gray. Maybe you are talking about this? https://github.com/cBioPortal/cbioportal/issues/2029

**Comment by adamabeshouse** [comment]
Do you have a link example?

**Comment by inodb** [comment]
@adamabeshouse Sorry, missed this. This is not for oncoprint but on the patient view in the genomic overview.

**Comment by inodb** [comment]
This case has mutation data, but simply has 0 mutations according to study view (should be changed to show genomic overview with 0 mutations):

http://www.cbioportal.org/case.do#/patient?caseId=P-0000053&studyId=msk_impact_2017

**Comment by jjgao** [comment]
Moving this to icebox. We will use igv.js -- not sure it it can take coverage data and show them.
