### ISSUE TITLE
lodash overloads global _

### ISSUE THREAD

**Issue by inodb** [cBioPortal/cbioportal-frontend#24]
It would seem that lodash overloads the global `_` variable, which makes it unusable in the context of the portal. Now we are just using underscore, but lodash is a superset of underscore, so in the future we would like to find a solution for this problem.

**Comment by brittanystoroz** [comment]
Is there something in particular this app needs underscore or lodash for? Most of the methods in those libraries are now available in ES6. (and it looks as if babel is being used?)

**Comment by inodb** [comment]
@brittanystoroz I don't think all of it is supported in ES6. Is there a groupBy in ES6? I also think chaining with underscore gives pretty readable code. Not sure if there's an equivalent in ES6.
