### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by wmnwmn** [cBioPortal/cbioportal-frontend#394]
I received this error following the build instructions ("npm run start") under npm version 5.0.3, on ubuntu. Prior steps (npm install, buildDLL) completed successfully. 

ERROR in ./src/shared/components/mutationTable/column/CosmicColumnFormatter.tsx
(106,13): error TS2322: Type 'number | undefined' is not assignable to type 'number'.
  Type 'undefined' is not assignable to type 'number'.
Child html-webpack-plugin for "index.html":

webpack: Failed to compile.

**Comment by alisman** [comment]
Can you try again and see if you still see this?

**Comment by alisman** [comment]
Also, what branch are you on?
