### ISSUE TITLE
refactor cBioPortal dataset page

### ISSUE THREAD

**Issue by JiaoJiao123** [cBioPortal/cbioportal-frontend#50]
I will try to refactor [cBioPortal dataset page](http://www.cbioportal.org/data_sets.jsp) under this new architecture. It only contains a table. Looks like a good place to start. But inside that table, we have various features like download file, search table content, sort by columns, mouse over etc. Those feature might take some time to implement. But I will start with a simple plain table.

**Comment by brittanystoroz** [comment]
You might find the [reactable](https://github.com/glittershark/reactable) library helpful. It helps create a table component and gives you a lot of features for free (sorting, filtering, etc.) The API is still a little rough around the edges, but overall I've found it more worth it than not.

**Comment by JiaoJiao123** [comment]
@brittanystoroz Thank you for your suggestion. And that is what I used for this implementation. I tried react-bootstrap-table and it had some style issue. So I switched to reactable.
