### ISSUE TITLE
Recurring request

### ISSUE THREAD

**Issue by oplantalech** [cBioPortal/cbioportal-frontend#625]
![captura de pantalla 2017-09-21 a les 15 12 37](https://user-images.githubusercontent.com/20278013/30697467-5f441562-9edf-11e7-8df3-33dfbc60ad3c.png)

**Comment by alisman** [comment]
What branch is this on?  I believe this will be fixed by next release.

**Comment by alisman** [comment]
Sorry, I didn't mean to close this

**Comment by oplantalech** [comment]
@alisman master, hotfix and rc have this problem.

**Comment by oplantalech** [comment]
This bug has disappeared, so I'm closing this issue.
