### ISSUE TITLE
TypeError: Cannot read property 'studyId' of undefined

### ISSUE THREAD

**Issue by khzhu** [cBioPortal/cbioportal-frontend#643]
here is how reproduce the error (see attached screenshot):
on query page

1. select a cancer study of interest
2. enter gene set by selecting "User-defined List" drop-down box 
3. click on "Submit Query" which brings you to the sample summary page
4. on Sample page click on "Mutations" tab
![screen shot 2017-09-28 at 12 12 48 pm](https://user-images.githubusercontent.com/17375786/30977712-60b2d700-a446-11e7-957f-35666c01a20e.png)

**Comment by jjgao** [comment]
@khzhu is this on rc branch?

**Comment by khzhu** [comment]
@jjgao , yes, I am using rc branch. 
the error can be reproduced from cbioportal.org/beta site too (please see attached). 
the error was `{"message":"Sample list not found: acbc_mskcc_2015_germline"}`

 {"message":"Sample list not found: acbc_mskcc_2015_germline"}"
![screen shot 2017-09-28 at 2 24 44 pm](https://user-images.githubusercontent.com/17375786/30983603-e8cf8afe-a458-11e7-96ba-b2f57dd4910d.png)

**Comment by jjgao** [comment]
@onursumer I remember you mentioned some issue about the mutations tab. Is this the issue?

**Comment by khzhu** [comment]
I confirmed this error has been fixed. Thanks!
