### ISSUE TITLE
Issue with CIVIC and CNA data?

### ISSUE THREAD

**Issue by pieterlukasse** [cBioPortal/cbioportal-frontend#674]
I just noticed an example of an unexpected CIVIC annotation. The alteration is AMP but the CIVIC information is about a DELETION:

![image](https://user-images.githubusercontent.com/2900303/31226956-6a5cd50c-a9d8-11e7-8375-973726dc0385.png)

I thought we were using AMP/DEL info to find a correct match, and if a correct match was not found but some other information about the gene *was* found, we would make the icon grey?

**Comment by pieterlukasse** [comment]
maybe the same issue as here https://github.com/cBioPortal/cbioportal/issues/2734 but then for CNA?

**Comment by pieterlukasse** [comment]
@jjgao @schultzn can you comment? I checked the PR https://github.com/cBioPortal/cbioportal/pull/2067, but could not find any details on whether this is expected behavior. I did a quick scan of this commit https://github.com/cBioPortal/cbioportal/pull/2067/commits/5647a45726f140a1da3cb828b0ab51f05b876f7e but found no logic separating AMP from DEL yet.

**Comment by schultzn** [comment]
We should definitely only show the annotation that matches the exact copy-number event.

**Comment by inodb** [comment]
deployed a while back
