### ISSUE TITLE
FRONTEND_VERSION & FRONTEND_HASH on Heroku

### ISSUE THREAD

**Issue by inodb** [cBioPortal/cbioportal-frontend#676]
Both these variables don't work on Heroku in 1.9.0 branch because in compilation phase `GIT_DIR` is unset. We could perhaps just serve jitpack artifacts directly (would also make our test environment more similar to our build env)

**Comment by inodb** [comment]
Serving artifacts from jitpack on Review Apps depends on this being solved: https://twitter.com/inodb/status/915972470800306178

**Comment by jjgao** [comment]
@inodb has this been solved?

**Comment by jjgao** [comment]
@inodb I am closing this. Please create a new one in the main repo if this is still relevant.
