### ISSUE TITLE
Use TypeScript autogenerated API client

### ISSUE THREAD

**Issue by inodb** [cBioPortal/cbioportal-frontend#70]
Currently using swagger JS client. Should move to TypeScript API

**Comment by adufilie** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Hello world w/ swagger api](https://trello.com/c/Mef48LDO/14-hello-world-w-swagger-api)

**Comment by adufilie** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [TS Swagger API generation](https://trello.com/c/j4BU0jYK/19-ts-swagger-api-generation)
