### ISSUE TITLE
Mutation table goes out of bounds when selecting multiple columns

### ISSUE THREAD

**Issue by inodb** [cBioPortal/cbioportal-frontend#790]
as reported by @ritikakundra 
![screen shot 2017-12-08 at 2 53 13 pm](https://user-images.githubusercontent.com/1334004/33782662-9a0ab43c-dc27-11e7-82a5-04d0f6714d24.png)

**Comment by jjgao** [comment]
iceboxed. We can revisit this when we are ready to expand the results page to full screen.

**Comment by oplantalech** [comment]
@jjgao Do you have any idea when this is going to be fixed?
