### ISSUE TITLE
Oncoprint re-renders after adding a new clinical track

### ISSUE THREAD

**Issue by pieterlukasse** [cBioPortal/cbioportal-frontend#801]
Steps to reproduce:
1- Load BRCA provisional TCGA study
2- Do a simple query on some genes
3- Click some of the clinical tracks. The oncoprint will completely re-render. See screenshot below:

![image](https://user-images.githubusercontent.com/2900303/33896155-67f6f422-df62-11e7-8762-7fa58e1553f1.png)

Desired solution: 

- The current tracks should stay. Oncoprint should not completely re-render. Just like when adding pre-calculated track such as "Total mutations"  and "Mutation spectrum" (after "Fraction Genome altered" has been added).

**Comment by adamabeshouse** [comment]
@alisman lets just use the full loader rectangle for the initial load, after that a smaller loader? 
@pieterlukasse the oncoprint isn't actually rerendering during this, it's just being obstructed by a loader while the data loads

**Comment by adamabeshouse** [comment]
@pieterlukasse this is a good catch we should address, but we're going to put this off until after the release

**Comment by jjgao** [comment]
add a zip line.

**Comment by adamabeshouse** [comment]
do we still want to do a zip line?

**Comment by pieterlukasse** [comment]
sounds good to me, as long as the oncoprint stays on the screen while new parts are added to it.

**Comment by adamabeshouse** [comment]
@pieterlukasse the oncoprint won't be usable while the new parts are added to it, but it could still be usable while the data is loading.

**Comment by pieterlukasse** [comment]
@adamabeshouse yes, I think it is just odd to have the whole thing disappear behind a grey curtain if all I am doing is just adding an extra clinical track.

**Comment by adamabeshouse** [comment]
@pieterlukasse I agree.. but to me it seems odd as well to have the oncoprint be visible when we cant interact with it. Maybe it would be better if we just made the gray transparent?

**Comment by jjgao** [comment]
Maybe show the loading message (small region) on top of OncoPrint?

**Comment by pieterlukasse** [comment]
@adamabeshouse I like @jjgao' s idea: perhaps just a small region with a progress bar?

**Comment by adamabeshouse** [comment]
I don't like that because then the oncoprint becomes unusable but theres no visual indication of that. What I think we should do is put a small "loading data" message somewhere while the data loads, but keep the oncoprint visible, since the oncoprint is still usable then. But then while the oncoprint renders, we'll put a transparent loader block on top.

**Comment by pieterlukasse** [comment]
@adamabeshouse sounds good :+1:

**Comment by adamabeshouse** [comment]
is this still something we'd like to do?

**Comment by pieterlukasse** [comment]
yes, if you ask me.

**Comment by jjgao** [comment]
I've moved it to Icebox. Let's not worry about it.

**Comment by pieterlukasse** [comment]
is icebox like a backlog or more like an archive?

**Comment by jjgao** [comment]
closing this. If still desired, please open in the main repo.
