### ISSUE TITLE
Spec Mutation data structure for API endpoint

### ISSUE THREAD

**Issue by onursumer** [cBioPortal/cbioportal-frontend#90]
related JSON model draft: https://script.google.com/macros/d/1fJ3GOG2o00_KD08Hbid7PNUOq8QVS_gR4Kc_-Fztn1HUPkdED5qypdsz/edit

**Comment by onursumer** [comment]
Legacy data that should not be part of the new mutation model anymore and should be retrieved by separate API calls or calculated on the front-end:

- cosmic
- genetic profile data: cna, mrna, cancer study, etc.
- links: patient view, study view, igv, etc.
- frequencies: tumor freq, normal freq
- mutation count
- mutsig
- key mut rate
- gene mut rate
- sanger
- tumor type?

**Comment by onursumer** [comment]
We also want to remove mutation assessor data and mutation event (annotation) data from the mutation model eventually.

**Comment by adamabeshouse** [comment]
shouldn't it be associated to a sample id, not a patient id? Or both?

**Comment by onursumer** [comment]
@adamabeshouse good catch! It should be sample id. Updated the documents accordingly.

**Comment by onursumer** [comment]
seems like `igvlinking.json` service is required to generate the linking for BAM column (on both the results and the patient view pages). Should we create another API endpoint for that, or try to resolve the linking on the client side?

Related legacy classes:

- [IGVLinking.java](https://github.com/cBioPortal/cbioportal/blob/c628bfc06e0f7446b4c2a51892f7acc8b6087325/core/src/main/java/org/mskcc/cbio/portal/util/IGVLinking.java)
- [IGVLinkingJSON.java](https://github.com/cBioPortal/cbioportal/blob/c628bfc06e0f7446b4c2a51892f7acc8b6087325/core/src/main/java/org/mskcc/cbio/portal/servlet/IGVLinkingJSON.java)

**Comment by adamabeshouse** [comment]
can we close this?
