### ISSUE TITLE
UnitProt in Mutation tab: Retrieved from database or MyGeneInfo?

### ISSUE THREAD

**Issue by sandertan** [cBioPortal/cbioportal-frontend#920]
@jjgao I noticed when entering an incorrect UniProtKB accession in my data in the SWISSPROT-column (for which the validator fails), this value is imported and saved in the database in the ONCOTATOR_UNIPROT_ACCESSION column. However, when if I query the gene, the UniProtKB name is correctly displayed in the Mutation Tab. This name is retrieved by first querying MyGene.info with the Entrez gene ID to retrieve the **accession** and then querying UniProt to retrieve the **name**.

For a gene which has a correct UniProtKB accession, MyGene.info is also queried to retrieve the UniProtKB accession. 

I was wondering if the SWISSPROT data from the database is still used in the Mutation Tab. It would be nice if this mechanism is documented in File-Formats.md. 

If the database is not used for the UniProtKB accession, it would mean that if MSK/a user would add their own isoforms in the SWISSPROT column (e.g. during vcf2maf), this data would not be shown in the front end.

**Comment by jjgao** [comment]
@sandertan we try to manage the portal issues (including frontend ones) in the portal repo. Would you mind moving this one there? Thanks.

**Comment by sandertan** [comment]
Ok! https://github.com/cBioPortal/cbioportal/issues/3802
