### ISSUE TITLE
make sampleheader own component

### ISSUE THREAD

**Issue by inodb** [cBioPortal/cbioportal-frontend#988]
It's getting kinda messy with a lot of logic in the render of PatientViewPage, especially with GDD added see:  https://github.com/cBioPortal/cbioportal-frontend/pull/724/files

**Comment by jjgao** [comment]
Issue moved to [cBioPortal/cbioportal #5647](https://github.com/cBioPortal/cbioportal/issues/5647) via [**ZenHub**](https://www.zenhub.com/)
